import type { Contest, LeaderboardRow, Notificare, Problem, Raportare, Submission, User } from '../types';

export const utilizatoriInitiali: User[] = [
  {
    id: 'u-admin',
    nume: 'Ana Ionescu',
    nickname: 'anaAdmin',
    email: 'admin@codepulse.ro',
    tara: 'România',
    limbajPreferat: 'python',
    rol: 'admin',
    rating: 2380,
    puncteTotale: 11420,
    clasamentGlobal: 1,
    insigne: ['Primii 10', 'Mentor de elită', 'Moderator'],
    esteBanat: false,
    concursuriCastigate: 7,
  },
  {
    id: 'u1',
    nume: 'Andrei Pop',
    nickname: 'andrei_dev',
    email: 'andrei@codepulse.ro',
    tara: 'România',
    limbajPreferat: 'cpp',
    rol: 'user',
    rating: 1820,
    puncteTotale: 7420,
    clasamentGlobal: 8,
    insigne: ['Primii 10', 'Rezolvare fulger'],
    esteBanat: false,
    concursuriCastigate: 2,
  },
  {
    id: 'u2',
    nume: 'Mihai Ilie',
    nickname: 'miki_js',
    email: 'mihai@codepulse.ro',
    tara: 'Republica Moldova',
    limbajPreferat: 'javascript',
    rol: 'user',
    rating: 1685,
    puncteTotale: 6130,
    clasamentGlobal: 14,
    insigne: ['Primii 20'],
    esteBanat: false,
    concursuriCastigate: 1,
  },
  {
    id: 'u3',
    nume: 'Elena Dobre',
    nickname: 'elena_algo',
    email: 'elena@codepulse.ro',
    tara: 'România',
    limbajPreferat: 'python',
    rol: 'user',
    rating: 1540,
    puncteTotale: 5520,
    clasamentGlobal: 23,
    insigne: ['Maratonist'],
    esteBanat: false,
    concursuriCastigate: 0,
  },
  {
    id: 'u4',
    nume: 'Radu Ceban',
    nickname: 'graph_wizard',
    email: 'radu@codepulse.ro',
    tara: 'România',
    limbajPreferat: 'java',
    rol: 'user',
    rating: 1960,
    puncteTotale: 8015,
    clasamentGlobal: 4,
    insigne: ['Primii 5', 'Rege Grafuri'],
    esteBanat: false,
    concursuriCastigate: 3,
  },
];

export const concursuriInitiale: Contest[] = [
  {
    id: 'c1',
    titlu: 'Neon Sprint #12',
    descriere:
      'Concurs rapid pe algoritmi clasici și optimizare. Focus pe implementare curată și viteză.',
    stare: 'activ',
    dificultate: 'mediu',
    tip: 'individual',
    startLa: '2026-02-16T18:00:00.000Z',
    finalLa: '2026-02-17T00:00:00.000Z',
    reguli: [
      'Este permisă doar o singură sesiune de concurs.',
      'Penalizare de 10 minute pentru fiecare soluție greșită.',
      'Clasamentul final folosește scor + timp total.',
    ],
    premii: ['500 EUR', '300 EUR', '200 EUR'],
    participanti: 412,
    problemeIds: ['p1', 'p2', 'p3', 'p4'],
  },
  {
    id: 'c2',
    titlu: 'Maraton Structuri de Date',
    descriere: 'Provocare de 8 ore pentru arbori, intervale și query-uri online.',
    stare: 'in_curand',
    dificultate: 'greu',
    tip: 'individual',
    startLa: '2026-02-20T10:00:00.000Z',
    finalLa: '2026-02-20T18:00:00.000Z',
    reguli: [
      'Nu este permis copy-paste din soluții externe.',
      'Soluțiile se evaluează pe seturi ascunse extinse.',
      'Primii 20 intră în finala lunară.',
    ],
    premii: ['Acces VIP la bootcamp', 'Merch premium'],
    participanti: 289,
    problemeIds: ['p5', 'p6', 'p7'],
  },
  {
    id: 'c3',
    titlu: 'Hack Duel Echipă vs Echipă',
    descriere: 'Concurs tactic în echipe, cu task-uri de grafuri și string matching.',
    stare: 'terminat',
    dificultate: 'mediu',
    tip: 'echipe',
    startLa: '2026-02-10T09:00:00.000Z',
    finalLa: '2026-02-10T14:00:00.000Z',
    reguli: [
      'Echipa are maxim 3 membri.',
      'Doar căpitanul poate trimite soluții oficiale.',
      'Se aplică tie-break după ultima soluție acceptată.',
    ],
    premii: ['Trofiu digital', 'Puncte bonus'],
    participanti: 150,
    problemeIds: ['p8', 'p9', 'p10'],
  },
  {
    id: 'c4',
    titlu: 'Arena de Încălzire',
    descriere: 'Concurs de intrare pentru participanți noi. Probleme scurte și feedback rapid.',
    stare: 'activ',
    dificultate: 'usor',
    tip: 'individual',
    startLa: '2026-02-16T12:00:00.000Z',
    finalLa: '2026-02-18T12:00:00.000Z',
    reguli: [
      'Se pot face trimiteri nelimitate.',
      'Primele 3 probleme au punctaj progresiv.',
    ],
    premii: ['Badge "Start puternic"'],
    participanti: 520,
    problemeIds: ['p11', 'p12', 'p13'],
  },
];

export const problemeInitiale: Problem[] = [
  {
    id: 'p1',
    contestId: 'c1',
    titlu: 'Sume Prefixate',
    enunt: 'Dat un vector, răspunde rapid la interogări de sumă pe interval [l, r].',
    inputExemplu: '5\n1 2 3 4 5\n2\n1 3\n2 5',
    outputExemplu: '6\n14',
    restrictii: ['1 <= n <= 2*10^5', '1 <= q <= 2*10^5'],
    punctaj: 120,
    dificultate: 'usor',
    taguri: ['prefix', 'array'],
  },
  {
    id: 'p2',
    contestId: 'c1',
    titlu: 'Rețea Minimă',
    enunt: 'Calculează costul minim pentru conectarea tuturor nodurilor din graf.',
    inputExemplu: '4 5\n1 2 3\n2 3 2\n3 4 5\n1 4 9\n1 3 4',
    outputExemplu: '10',
    restrictii: ['2 <= n <= 10^5', '1 <= m <= 2*10^5'],
    punctaj: 240,
    dificultate: 'mediu',
    taguri: ['grafuri', 'mst'],
  },
  {
    id: 'p3',
    contestId: 'c1',
    titlu: 'Șir Alternant',
    enunt: 'Determină lungimea maximă a unui subșir alternant strict.',
    inputExemplu: '6\n1 7 4 9 2 5',
    outputExemplu: '6',
    restrictii: ['1 <= n <= 10^5'],
    punctaj: 200,
    dificultate: 'mediu',
    taguri: ['dp', 'greedy'],
  },
  {
    id: 'p4',
    contestId: 'c1',
    titlu: 'Ferestre Binare',
    enunt: 'Numără subsecvențele cu exact k biți de 1.',
    inputExemplu: '010101\n2',
    outputExemplu: '6',
    restrictii: ['1 <= |s| <= 2*10^5'],
    punctaj: 260,
    dificultate: 'greu',
    taguri: ['two-pointers', 'string'],
  },
  {
    id: 'p5',
    contestId: 'c2',
    titlu: 'Arbore de Intervale Dinamic',
    enunt: 'Suportă update-uri punctuale și query de maxim pe interval.',
    inputExemplu: '8 3\n1 2 3 4 5 6 7 8\nmax 1 8\nset 3 20\nmax 1 4',
    outputExemplu: '8\n20',
    restrictii: ['n <= 2*10^5', 'operații <= 2*10^5'],
    punctaj: 300,
    dificultate: 'greu',
    taguri: ['segment-tree'],
  },
  {
    id: 'p6',
    contestId: 'c2',
    titlu: 'Teleportare în Graf',
    enunt: 'Găsește cel mai scurt drum când unele noduri permit teleport.',
    inputExemplu: '5 6\n1 2\n2 3\n3 4\n4 5\n1 5\n2 4',
    outputExemplu: '2',
    restrictii: ['n <= 10^5', 'm <= 2*10^5'],
    punctaj: 320,
    dificultate: 'greu',
    taguri: ['grafuri', 'dijkstra'],
  },
  {
    id: 'p7',
    contestId: 'c2',
    titlu: 'Compresie de Stringuri',
    enunt: 'Minimizează lungimea codării pentru un șir dat.',
    inputExemplu: 'aaabbbbbcccc',
    outputExemplu: 'a3b5c4',
    restrictii: ['1 <= n <= 10^5'],
    punctaj: 250,
    dificultate: 'mediu',
    taguri: ['string', 'implementare'],
  },
  {
    id: 'p8',
    contestId: 'c3',
    titlu: 'Labirint Competitiv',
    enunt: 'Alege traseul minim într-un grid cu obstacole și costuri variabile.',
    inputExemplu: '3 3\n1 1 2\n2 9 1\n3 1 1',
    outputExemplu: '7',
    restrictii: ['n,m <= 1000'],
    punctaj: 220,
    dificultate: 'mediu',
    taguri: ['bfs', 'grid'],
  },
  {
    id: 'p9',
    contestId: 'c3',
    titlu: 'Frecvențe în Flux',
    enunt: 'Procesează un flux și răspunde la cele mai frecvente k valori.',
    inputExemplu: '8\n1 1 2 2 2 3 4 4\n2',
    outputExemplu: '2 1',
    restrictii: ['n <= 5*10^5'],
    punctaj: 180,
    dificultate: 'usor',
    taguri: ['hash', 'heap'],
  },
  {
    id: 'p10',
    contestId: 'c3',
    titlu: 'LCS Turbo',
    enunt: 'Determină lungimea celui mai lung subsir comun pentru două stringuri.',
    inputExemplu: 'ABCDGH\nAEDFHR',
    outputExemplu: '3',
    restrictii: ['n,m <= 3000'],
    punctaj: 260,
    dificultate: 'greu',
    taguri: ['dp', 'string'],
  },
  {
    id: 'p11',
    contestId: 'c4',
    titlu: 'Număr Prim Rapid',
    enunt: 'Verifică dacă un număr este prim.',
    inputExemplu: '29',
    outputExemplu: 'DA',
    restrictii: ['1 <= n <= 10^9'],
    punctaj: 80,
    dificultate: 'usor',
    taguri: ['math'],
  },
  {
    id: 'p12',
    contestId: 'c4',
    titlu: 'Rotire Array',
    enunt: 'Rotește un vector la dreapta cu k poziții.',
    inputExemplu: '5 2\n1 2 3 4 5',
    outputExemplu: '4 5 1 2 3',
    restrictii: ['n <= 10^5'],
    punctaj: 100,
    dificultate: 'usor',
    taguri: ['array', 'implementare'],
  },
  {
    id: 'p13',
    contestId: 'c4',
    titlu: 'Paranteze Echilibrate',
    enunt: 'Verifică dacă o expresie cu paranteze este validă.',
    inputExemplu: '([]{})',
    outputExemplu: 'VALID',
    restrictii: ['n <= 10^5'],
    punctaj: 120,
    dificultate: 'mediu',
    taguri: ['stack', 'string'],
  },
];

export const trimiteriInitiale: Submission[] = [
  {
    id: 's1',
    userId: 'u1',
    contestId: 'c1',
    problemId: 'p1',
    limbaj: 'cpp',
    cod: '#include <bits/stdc++.h>\nint main(){return 0;}',
    rezultat: 'acceptat',
    scor: 120,
    trimisLa: '2026-02-16T18:30:00.000Z',
  },
  {
    id: 's2',
    userId: 'u1',
    contestId: 'c1',
    problemId: 'p2',
    limbaj: 'cpp',
    cod: '// tentativa 1',
    rezultat: 'gresit',
    scor: 0,
    trimisLa: '2026-02-16T19:00:00.000Z',
  },
  {
    id: 's3',
    userId: 'u2',
    contestId: 'c4',
    problemId: 'p11',
    limbaj: 'javascript',
    cod: 'console.log("DA")',
    rezultat: 'acceptat',
    scor: 80,
    trimisLa: '2026-02-16T13:00:00.000Z',
  },
];

export const clasamentGlobalInitial: LeaderboardRow[] = [
  { userId: 'u-admin', nickname: 'anaAdmin', rating: 2380, puncte: 11420, rank: 1, deltaRating: +12 },
  { userId: 'u4', nickname: 'graph_wizard', rating: 1960, puncte: 8015, rank: 2, deltaRating: +8 },
  { userId: 'u1', nickname: 'andrei_dev', rating: 1820, puncte: 7420, rank: 3, deltaRating: +15 },
  { userId: 'u2', nickname: 'miki_js', rating: 1685, puncte: 6130, rank: 4, deltaRating: -6 },
  { userId: 'u3', nickname: 'elena_algo', rating: 1540, puncte: 5520, rank: 5, deltaRating: +4 },
];

export const clasamentePeConcursInitial: Record<string, LeaderboardRow[]> = {
  c1: [
    { userId: 'u4', nickname: 'graph_wizard', rating: 1960, puncte: 540, rank: 1, deltaRating: +9 },
    { userId: 'u1', nickname: 'andrei_dev', rating: 1820, puncte: 420, rank: 2, deltaRating: +6 },
    { userId: 'u2', nickname: 'miki_js', rating: 1685, puncte: 300, rank: 3, deltaRating: -2 },
    { userId: 'u3', nickname: 'elena_algo', rating: 1540, puncte: 280, rank: 4, deltaRating: +3 },
  ],
  c2: [
    { userId: 'u1', nickname: 'andrei_dev', rating: 1820, puncte: 0, rank: 1, deltaRating: 0 },
    { userId: 'u4', nickname: 'graph_wizard', rating: 1960, puncte: 0, rank: 2, deltaRating: 0 },
  ],
  c3: [
    { userId: 'u-admin', nickname: 'anaAdmin', rating: 2380, puncte: 640, rank: 1, deltaRating: +10 },
    { userId: 'u2', nickname: 'miki_js', rating: 1685, puncte: 490, rank: 2, deltaRating: +5 },
    { userId: 'u3', nickname: 'elena_algo', rating: 1540, puncte: 410, rank: 3, deltaRating: +2 },
  ],
  c4: [
    { userId: 'u2', nickname: 'miki_js', rating: 1685, puncte: 180, rank: 1, deltaRating: +7 },
    { userId: 'u3', nickname: 'elena_algo', rating: 1540, puncte: 130, rank: 2, deltaRating: +3 },
  ],
};

export const notificariPeUtilizatorInitiale: Record<string, Notificare[]> = {
  u1: [
    {
      id: 'n1',
      mesaj: 'Ai urcat 2 poziții în clasamentul global.',
      tip: 'succes',
      creatLa: '2026-02-16T20:00:00.000Z',
    },
    {
      id: 'n2',
      mesaj: 'Concurs nou disponibil: Maraton Structuri de Date.',
      tip: 'info',
      creatLa: '2026-02-15T12:00:00.000Z',
    },
  ],
  u2: [
    {
      id: 'n3',
      mesaj: 'Ai primit insigna "Primii 20".',
      tip: 'succes',
      creatLa: '2026-02-14T09:30:00.000Z',
    },
  ],
};

export const raportariInitiale: Raportare[] = [
  {
    id: 'r1',
    tip: 'solutie',
    raportatDe: 'andrei_dev',
    tinta: 's2',
    motiv: 'Soluție suspectă de plagiat.',
    status: 'nou',
    creatLa: '2026-02-16T11:00:00.000Z',
  },
  {
    id: 'r2',
    tip: 'utilizator',
    raportatDe: 'miki_js',
    tinta: 'u3',
    motiv: 'Limbaj nepotrivit în chat-ul concursului.',
    status: 'in_analiza',
    creatLa: '2026-02-15T17:20:00.000Z',
  },
];
